name: pam-vgn
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - pytorch
  - torchvision
  - torchaudio
  - torchmetrics
  - pyg  # torch-geometric
  - pip
  - pip:
      # in case some packages need pip installs
      - torch-geometric-temporal